language: c
addons:
  apt_packages:
    - make
    - git
    - groff
    - ncurses-dev
    - exuberant-ctags
  homebrew:
    packages:
      - make
      - git
      - groff
      - ncurses
      - ctags
branches:
 - moraes
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
arch:
 - amd64
 - arm64
 - ppc64le
 - s390x
script:
 - o="-O3 -Wall -pedantic"; u=$(uname); case $u in Linux) make OPTFLAGS="$o" SYSDEFS=-DXLINUX TERMCAPLIB=-lncurses; make clean; make OPTFLAGS="$o" SYSDEFS='-DBAREBONES -DJTC'; make clean; make OPTFLAGS="$o" SYSDEFS='-DPIPEPROCS -DPOSIX_PROCS';; Darwin) make OPTFLAGS="$o" SYSDEFS=-DXBSD TERMCAPLIB=-lncurses;; *) echo "Unknown uname \"$u\"";; esac
