language: c
addons:
  apt_packages:
    - make
    - git
    - groff
    - ncurses-dev
    - exuberant-ctags
    - zip
  homebrew:
    packages:
      - make
      - git
      - groff
      - ncurses
      - ctags
      - zip
branches:
 - moraes
os:
 - linux
 - osx
compiler:
 - gcc
arch:
 - amd64
 - arm64
 - ppc64le
 - s390x
script:
 - |
    set -eux
    td=$(mktemp -d)
    dd="DESTDIR=$td"
    o="-Os -Wall -pedantic"
    u=$(uname)
    d=
    x=
    case $u in
    *BSD)   e=-lutil
            t=-ltermcap
            if test -x /usr/bin/getconf; then j=-j$(getconf NPROCESSORS_ONLN); else j=; fi
            ;;
    SunOS)  e=
            t=-ltermcap
            u=SYSVR4
            o=-O
            j="NROFF=nroff TROFF=troff"
            d="-DREALSTDC"
            ur=$(uname -r)
            case "$ur" in
            5.0) x="-DGRANTPT_BUG";;
            5.*) ;;
            *) echo "$0: Not set up for testing $u $ur" >&2; exit 1;;
            esac
            xi=/usr/gnu/bin/install
            if test ! -x $xi; then
                xi=cp
            fi
            x="XINSTALL=$xi TINSTALL=$xi"
            ;;
    *)      e=
            t=-lncurses
            if test -x /usr/bin/getconf; then j=-j$(getconf _NPROCESSORS_ONLN); else j=; fi
            ;;
    esac
    make $j OPTFLAGS="$o" SYSDEFS=-D$u TERMCAPLIB=$t EXTRALIBS=$e $x $dd/t10-$u install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DTERMIOS -DPIPEPROCS -DPOSIX_PROCS $d" $x TERMCAPLIB=$t $dd/t20-pipeprocs install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DBSDPOSIX $d" TERMCAPLIB=$t $x $dd/t30-bsdposix install &&
    make clean &&
    case "$u" in
    Linux)
        make $j OPTFLAGS="$o" SYSDEFS="-DGLIBCPTY" TERMCAPLIB=$t EXTRALIBS=-lutil $x $dd/t40-glibcpty install &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS="-DTERMINFO -DUSE_VFORK" TERMCAPLIB=$t $x $dd/t50-vfork &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS='-DBAREBONES -DSMALL -DJTC' TERMCAPLIB= $x $dd/t60-small install &&
        make clean
        ;;
    esac &&
    make distrib jovedoss.zip &&
    find $td -ls &&
    rm -rf $td &&
    set +u
