# test Jove build on a variety of Travis-CI platforms
# Mark Moraes, 20210212
language: c
addons:
  apt_packages: 
    - &common [make, groff, ctags, zip ]
    - &apts [ ncurses-dev ]
  homebrew:
    packages: &brews [ ncurses, *common ]
    update: true
os: [ linux, osx ]
compiler: [gcc, clang ]
arch: &archs [amd64, arm64, ppc64le]
jobs:
  # now modify the build matrix constructed above
  exclude:
    # REMOVE gcc on osx (it is just clang)
    - os: osx
      compiler: gcc
  include:
    # ADD an explicit osx homebrew gcc-7 (i.e. not clang)
    - os: osx
      env: CC=gcc-7
      addons:
        homebrew:
          packages: [gcc@7, *brews]
          update: true
    # ADD latest gcc (-9) on default linux amd64 (xenial),
    - os: linux
      env: CC=gcc-9
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [gcc-9, *apts, *common]
    # ADD oldest and newest versions of xcode and linux
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode11.3
    - os: linux
      dist: trusty
      arch: amd64
      addons:
        apt_packages: [*apts, *common]
    - os: linux
      dist: focal
      arch: amd64
      addons:
        apt_packages: [*apts, *common]
    - os: linux
      dist: bionic
      arch: amd64
      addons:
        apt_packages: [*apts, *common]
    - os: linux
      dist: bionic
      arch: arm64
      addons:
        apt_packages: [*apts, *common]
script:
  - |
    set -eux
    # note: older *BSD, OSX, Solaris require a template
    td=$(mktemp -d "${TMPDIR:-/tmp}/jvt.XXXXXXXX")
    dd="DESTDIR=$td"
    u=$(uname)
    o=-O
    e=
    d=
    x=
    d=-DTERMIOS
    t=-ltermcap
    lib=
    jv=NPROCESSORS_ONLN
    case $u in
    SunOS)  x="NROFF=nroff TROFF=troff"
            d="-DREALSTDC -DPOSIX_PROCS"
            ur=$(uname -r)
            case "$ur" in
            5.0) d="-DSYSVR4 -DGRANTPT_BUG";;
            5.*) ;;
            *) echo "$0: Not set up for testing $u $ur" >&2; exit 1;;
            esac
            xi=/usr/gnu/bin/install
            if test ! -x $xi; then
                xi=cp
            fi
            x="$x XINSTALL=$xi TINSTALL=$xi"
            ;;
    Linux)  t=-lncurses
            if test -e /etc/alpine-release; then
                d="$d -DUSE_GETCWD"; lib=MUSL;
            elif test -e /etc/gentoo-release; then
                t="-ltinfo"; lib=GLIBC;
            else
                lib=GLIBC;
            fi
            jv=_NPROCESSORS_ONLN
            ;;
    esac
    if test -x /usr/bin/getconf; then j=-j$(getconf $jv); else j=; fi
    # other than the first "make install" with $u, some of the others
    # (e.g. PIPEPROCS, TERMINFO) may produce warnings (e.g. no declaration for
    # ioctl) because we are just testing somewhat abnormal non-POSIX sysdefs.
    make clean &&
    make $j $x $dd/t10-$u install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DPIPEPROCS $d" TERMCAPLIB=$t $x $dd/t20-pipeprocs install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DBSDPOSIX $d" TERMCAPLIB=$t $x $dd/t30-bsdposix install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DBAREBONES -DSMALL -DJTC $d" TERMCAPLIB= $x $dd/t60-small install &&
    make clean &&
    case "$lib" in
    GLIBC)
        make $j OPTFLAGS="$o" SYSDEFS="-DGLIBCPTY" TERMCAPLIB=$t EXTRALIBS=-lutil $x $dd/t40-glibcpty install &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS="-DTERMINFO -DUSE_VFORK" TERMCAPLIB=$t $x $dd/t50-vfork &&
        make clean
        ;;
    esac &&
    make $x tgz &&
    if type zip 2> /dev/null; then make $x zip; fi &&
    ls -s $(find $td | grep /bin/) &&
    rm -rf $td &&
    set +u
