language: c
addons:
  apt_packages:
    - make
    - git
    - groff
    - ncurses-dev
    - exuberant-ctags
    - zip
  homebrew:
    packages:
      - make
      - git
      - groff
      - ncurses
      - ctags
      - zip
branches:
 - moraes
os:
 - linux
 - osx
compiler:
 - gcc
arch:
 - amd64
 - arm64
 - ppc64le
 - s390x
script:
 - |
    set -eux
    o="-Os -Wall -pedantic"
    u=$(uname)
    case $u in
    *BSD)   e=-lutil
            t=-ltermcap
	    if test -x /usr/bin/getconf; then j=-j$(getconf NPROCESSORS_ONLN); else j=; fi
            ;;
    SunOS)  e=
            t=-ltermcap
	    u=SYSVR4
	    if test -x /usr/bin/getconf; then j=-j$(getconf NPROCESSORS_ONLN); else j=; fi
            ;;
    *)      e=
            t=-lncurses
	    if test -x /usr/bin/getconf; then j=-j$(getconf _NPROCESSORS_ONLN); else j=; fi
            ;;
    esac
    make $j OPTFLAGS="$o" SYSDEFS=-D$u TERMCAPLIB=$t EXTRALIBS=$e &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS='-DTERMIOS -DPIPEPROCS -DPOSIX_PROCS' TERMCAPLIB=$t &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DBSDPOSIX" TERMCAPLIB=$t &&
    make clean &&
    case "$u" in
    Linux)
        make $j OPTFLAGS="$o" SYSDEFS="-DGLIBCPTY" TERMCAPLIB=$t EXTRALIBS=-lutil &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS="-DTERMINFO -DUSE_VFORK" TERMCAPLIB=$t &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS='-DBAREBONES -DSMALL -DJTC' TERMCAPLIB= &&
        make clean
        ;;
    esac &&
    make distrib jovedoss.zip &&
    set +u
