language: c
addons:
  apt_packages:
    - make
    - git
    - groff
    - ncurses-dev
    - exuberant-ctags
    - zip
  homebrew:
    packages:
      - make
      - git
      - groff
      - ncurses
      - ctags
      - zip
branches:
 - moraes
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
arch:
 - amd64
 - arm64
 - ppc64le
 - s390x
script:
 - |
    o="-O3 -Wall -pedantic"
    u=$(uname)
    case $u in
    *BSD)   e=-lutil
            t=-ltermcap
            ;;
    *)      e=
            t=-lncurses
            ;;
    esac
    make OPTFLAGS="$o" SYSDEFS=-D$u TERMCAPLIB=$t EXTRALIBS=$e
    make clean
    make OPTFLAGS="$o" SYSDEFS='-DBAREBONES -DSMALL -DJTC'
    make clean
    make OPTFLAGS="$o" SYSDEFS='-DPIPEPROCS -DPOSIX_PROCS'
    make clean
    make OPTFLAGS="$o" SYSDEFS='-D$u -DUSE_VFORK' TERMCAPLIB=$t EXTRALIBS=$e
    make clean
    make distrib jovedoss.zip
