# test Jove build on a variety of Travis-CI platforms
# Mark Moraes, 20200221
language: c
addons:
  apt_packages: 
    - &common [make, groff, ctags, zip ]
    - &apts [ ncurses-dev ]
  homebrew:
    packages: &brews [ ncurses, *common ]
branches: [ moraes ]
os: [ linux, osx ]
compiler: [gcc, clang ]
arch: &archs [amd64, arm64, ppc64le, s390x]
jobs:
  # now modify the build matrix constructed above
  exclude:
    # REMOVE gcc on osx (it is just clang)
    - os: osx
      compiler: gcc
  include:
    # ADD an explicit osx homebrew gcc-7 (i.e. not clang)
    - os: osx
      env: CC=gcc-7
      addons:
        homebrew:
          packages: [gcc@7, *brews]
	update: true
    # ADD latest gcc (-9) on default linux amd64 (xenial),
    - os: linux
      env: CC=gcc-9
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [gcc-9, *apts, *common]
    # ADD oldest and newest versions of xcode and linux
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode11.3
    - os: linux
      dist: precise
      arch: amd64
      addons:
        apt_packages: [*apts, *common]
    - os: linux
      dist: bionic
      arch: amd64
      addons:
        apt_packages: [*apts, *common]
    - os: linux
      dist: bionic
      arch: arm64
      addons:
        apt_packages: [*apts, *common]
script:
  - |
    set -eux
    # note: older *BSD, OSX, Solaris require a template
    td=$(mktemp -d "${TMPDIR:-/tmp}/jvt.XXXXXXXX")
    dd="DESTDIR=$td"
    o="-Os -Wall -pedantic"
    u=$(uname)
    d=
    x=
    case $u in
    *BSD)   e=-lutil
            t=-ltermcap
            if test -x /usr/bin/getconf; then j=-j$(getconf NPROCESSORS_ONLN); else j=; fi
            ;;
    SunOS)  e=
            t=-ltermcap
            u=SYSVR4
            o=-O
            j="NROFF=nroff TROFF=troff"
            d="-DREALSTDC"
            ur=$(uname -r)
            case "$ur" in
            5.0) x="-DGRANTPT_BUG";;
            5.*) ;;
            *) echo "$0: Not set up for testing $u $ur" >&2; exit 1;;
            esac
            xi=/usr/gnu/bin/install
            if test ! -x $xi; then
                xi=cp
            fi
            x="XINSTALL=$xi TINSTALL=$xi"
            ;;
    *)      e=
            t=-lncurses
            if test -x /usr/bin/getconf; then j=-j$(getconf _NPROCESSORS_ONLN); else j=; fi
            ;;
    esac
    make $j OPTFLAGS="$o" SYSDEFS=-D$u TERMCAPLIB=$t EXTRALIBS=$e $x $dd/t10-$u install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DTERMIOS -DPIPEPROCS -DPOSIX_PROCS $d" $x TERMCAPLIB=$t $dd/t20-pipeprocs install &&
    make clean &&
    make $j OPTFLAGS="$o" SYSDEFS="-DBSDPOSIX $d" TERMCAPLIB=$t $x $dd/t30-bsdposix install &&
    make clean &&
    case "$u" in
    Linux)
        make $j OPTFLAGS="$o" SYSDEFS="-DGLIBCPTY" TERMCAPLIB=$t EXTRALIBS=-lutil $x $dd/t40-glibcpty install &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS="-DTERMINFO -DUSE_VFORK" TERMCAPLIB=$t $x $dd/t50-vfork &&
        make clean &&
        make $j OPTFLAGS="$o" SYSDEFS='-DBAREBONES -DSMALL -DJTC' TERMCAPLIB= $x $dd/t60-small install &&
        make clean
        ;;
    esac &&
    make distrib jovedoss.zip &&
    find $td -ls &&
    rm -rf $td &&
    set +u
